name: wind
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  flutter_bloc: ^8.0.0
  json_serializable: ^6.1.3
  google_fonts: ^2.1.1
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  bloc_test: ^9.0.1
  test: ^1.14.4
  test_api: ^0.4.3
  flutter_native_splash: ^1.3.2
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
flutter_native_splash:
  color: "#ffffff"